version: '3'
services:
  xm_company:
    image: xm-company:staging
    restart: always
    container_name: xm_company_api_staging
    ports:
      - 8080:8080
    environment:
      XM_COMPANY_CONFIG: /app
      XM_COMPANY_DATASOURCES_MONGO_HOST: xm_mongo
      XM_COMPANY_DATASOURCES_MONGO_USERNAME: 49L2ww2j7mo66chG7G
      XM_COMPANY_DATASOURCES_MONGO_PASSWORD: wdF8V4x3qw946p486n
      XM_COMPANY_EVENTS_BROCKER_ADDR: kafka:9092
      XM_COMPANY_ROUTER_AUTH_JWT_KEY: "bzIwVTFgSopRBJ5KLZf0XPyHlUs+rFi6uFkuTEcfkgE="
      XM_COMPANY_ROUTER_AUTH_USERNAME: Camille
      XM_COMPANY_ROUTER_AUTH_PASSWORD: Lange

  xm_mongo:
    image: mongo
    restart: always
    container_name: xm_mongo_staging
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 49L2ww2j7mo66chG7G
      MONGO_INITDB_ROOT_PASSWORD: wdF8V4x3qw946p486n
  
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - "9094:9094"

  kafka-ui:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafka-ui
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka

  