version: '3'
services:
  xm_compagny:
    image: xm-compagny:staging
    restart: always
    container_name: xm_compagny_api_staging
    ports:
      - 8080:8080
    environment:
      XM_COMPAGNY_CONFIG: /app
      XM_COMPAGNY_DATASOURCES_MONGO_HOST: xm_mongo
      XM_COMPAGNY_DATASOURCES_MONGO_USERNAME: 49L2ww2j7mo66chG7G
      XM_COMPAGNY_DATASOURCES_MONGO_PASSWORD: wdF8V4x3qw946p486n
  xm_mongo:
    image: mongo
    restart: always
    container_name: xm_mongo_staging
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 49L2ww2j7mo66chG7G
      MONGO_INITDB_ROOT_PASSWORD: wdF8V4x3qw946p486n

  