version: '3'
services:
  xm_mongo:
    image: mongo
    restart: always
    container_name: xm_mongo_dev
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # TODO : change me. Use this for dev only 
      MONGO_INITDB_ROOT_PASSWORD: root # TODO : change me. Use this for dev only 
  
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
    ports:
      - "9094:9094"

  kafka-ui:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafka-ui
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - "9000:9000"
    depends_on:
      - kafka