datasources:
  mongo:
    db: xm_company
    host: localhost
    port: 27017
    username: root
    password: root
    timeout: 10

events:
  brocker_addr: localhost:9094
  topic: xm_company_api

router:
  addr: ""
  port: 8080
  gin_mode: release
  shutdown_timeout: 5
  auth:
    jwt_key: j0Qm7uwnzxeS3UL6PNMQieXYO1XSU2l033U+2HggPw4=
    username: test
    password: test