datasources:
  mongo:
    db: xm_company
    host: localhost
    port: 27017
    username: root
    password: root
    timeout: 10


router:
  addr: ""
  port: 8080
  gin_mode: release
  shutdown_timeout: 5