datasources:
  mongo:
    db: xm_company
    host: localhost
    port: 27017
    username: root
    password: root
    timeout: 10

events:
  brocker_addr: localhost:9094
  topic: xm_company_api

router:
  addr: ""
  port: 8080
  gin_mode: release
  shutdown_timeout: 5