openapi: '3.0.3'
info:
  title: XM-company
  version: '1.0'
paths:
  /login:
    post:
      description: "Authenticate a user and return a JWT token"
      summary: "Login endpoint for JWT authentication"
      tags: 
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: "Successful login with JWT token"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "500":
          $ref: "#/components/responses/InternalServerError"

  /company:
    post:
      description: "Create a company"
      summary: "Create a company"
      tags:
        - Company
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: "Bearer token for authentication"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_company"
      responses:
        "200":
          description: "A successful response with the new company UUID"
          content:
            application/json:
              schema:
                type: string
                format: uuid
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

    get:
      description: "An endpoint to get all companies"
      summary: "An endpoint to get all companies"
      tags:
        - Company
      responses:
        "200":
          description: "a successfull response with the companies"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/company"
        "400":
          $ref: "#/components/responses/BadRequest"

  /company/{company_uuid}:
    parameters:
      - in: path
        name: company_uuid
        required: true
        schema:
          type: string
          format: uuid

    get:
      description: "An endpoint to get a company with it's uuid"
      summary: "An endpoint to get a company with it's uuid"
      tags:
        - Company
      responses:
        "200":
          description: "a successfull response with the company"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/company"
        "400":
          $ref: "#/components/responses/BadRequest"

    put:
      description: "Update a company"
      summary: "Update a company"
      tags:
        - Company
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: "Bearer token for authentication"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/post_company"
      responses:
        "204":
          description: "A successful response with no content"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

    delete:
      description: "Delete a company"
      summary: "Delete a company"
      tags:
        - Company
      security:
        - bearerAuth: []
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: "Bearer token for authentication"
      responses:
        "204":
          description: "A successful response with no content"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    company:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
        employees_number:
          type: number
        registered:
          type: boolean
        type:
          type: string
          enum: ["Corporation", "Non Profit", "Cooperative", "Sole Proprietorship"]
    post_company:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        employees_number:
          type: number
        registered:
          type: boolean
        type:
          type: string
          enum: ["Corporation", "Non Profit", "Cooperative", "Sole Proprietorship"]
  responses:
    BadRequest:
      description: "An error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    Unauthorized:
      description: "An error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
    InternalServerError:
      description: "An error response"
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string